# Generated by Django 4.2.3 on 2023-07-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('hstateour', models.IntegerField()),
                ('cre', models.CharField(max_length=255)),
                ('its', models.IntegerField()),
            ],
        ),
    ]
